<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">


    <xacro:property name="chassis_width" value="0.23495"/>
    <xacro:property name="wheel_radius" value="0.060325"/>
    <xacro:property name="wheel_width" value="0.060325"/>


    <gazebo>
        <plugin name='diff_drive' filename='libgazebo_ros_diff_drive.so'>


        <!-- wheels -->
        <num_wheel_pairs>2</num_wheel_pairs>
        <left_joint>left_front_wheel_joint</left_joint>
        <left_joint>left_rear_wheel_joint</left_joint>
        <right_joint>right_front_wheel_joint</right_joint>
        <right_joint>right_rear_wheel_joint</right_joint>

        <!-- kinematics -->
        <wheel_separation>${chassis_width+(wheel_width/2)}</wheel_separation>
        <wheel_diameter>${2*wheel_radius}</wheel_diameter>

        <!-- limits -->
        <max_wheel_torque>50</max_wheel_torque>
        <max_wheel_acceleration>2.0</max_wheel_acceleration>

        <!-- output -->
        <publish_odom>true</publish_odom>
        <publish_odom_tf>true</publish_odom_tf>
        <publish_wheel_tf>true</publish_wheel_tf>

        <odometry_frame>odom</odometry_frame>
        <robot_base_frame>base_link</robot_base_frame>

        </plugin>
    </gazebo>
</robot>