<?xml version="1.0"?>



<robot xmlns:xacro="http://www.ros.org/wiki/xacro">


    <xacro:include filename="inertial_macros.xacro"/>


    <xacro:property name="chassis_length" value="0.24765"/>
    <xacro:property name="chassis_width" value="0.23495"/>
    <xacro:property name="chassis_height" value="0.060325"/>

    <xacro:property name="wheel_radius" value="0.060325"/>
    <xacro:property name="wheel_width" value="0.060325"/>

    <xacro:property name="basis_wheel_x_distance" value="0.0936625"/>
    <xacro:property name="basis_wheel_y_distance" value="${(chassis_width/2)+(wheel_width/2)}"/>
    <xacro:property name="basis_wheel_z_distance" value="-0.01349375"/>


    <material name="gray">
        <color rgba="0.5 0.5 0.5 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>


    <!--base link-->

    <link name="base_link">
    </link>


    <!--chassis joint link-->

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="${-chassis_length/2} 0 ${-chassis_height/2}"/>
    </joint>

    <link name="chassis">
        <visual>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="gray"/>
        </visual>
        <collision>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>


    <!--front left wheel joint link-->

    <joint name="front_left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="front_left_wheel"/>
        <origin xyz="${basis_wheel_x_distance} ${basis_wheel_y_distance} ${basis_wheel_z_distance}" rpy="-${pi/2} 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>

    <link name="front_left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.1" length="${wheel_width}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>


    <!--front right wheel joint link-->

    <joint name="front_right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="front_right_wheel"/>
        <origin xyz="${basis_wheel_x_distance} -${basis_wheel_y_distance} ${basis_wheel_z_distance}" rpy="${pi/2} 0 0"/>
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="front_right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.1" length="${wheel_width}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>


    <!--rear left wheel joint link-->

    <joint name="rear_left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="rear_left_wheel"/>
        <origin xyz="-${basis_wheel_x_distance} ${basis_wheel_y_distance} ${basis_wheel_z_distance}" rpy="-${pi/2} 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>

    <link name="rear_left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.1" length="${wheel_width}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>


    <!--rear right wheel joint link-->

    <joint name="rear_right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="rear_right_wheel"/>
        <origin xyz="-${basis_wheel_x_distance} -${basis_wheel_y_distance} ${basis_wheel_z_distance}" rpy="${pi/2} 0 0"/>
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="rear_right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.1" length="${wheel_width}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>


</robot>